export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const WORKOUTS_LOADED = 'WORKOUTS_LOADED';
export const ADD_SELECTED_EXERCISE = 'ADD_SELECTED_EXERCISE';
export const REMOVE_SELECTED_EXERCISE = 'REMOVE_SELECTED_EXERCISE';
export const EDIT_WORKOUT_LOADED = 'EDIT_WORKOUT_LOADED';
export const SELECT_WORKOUT = 'SELECT_WORKOUT';
export const EDIT_WORKOUT_NAME = 'EDIT_WORKOUT_NAME';
